[package]
name = "harmonia-daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
harmonia-utils-io = { version = "0.0.0-alpha.0" }
harmonia-utils-hash = { version = "0.0.0-alpha.0" }
harmonia-store-core = { version = "0.0.0-alpha.0" }
harmonia-store-db = { version = "3.0.0" }
harmonia-protocol = { version = "3.0.0" }
tokio = { workspace = true }
tracing = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
harmonia-utils-test = { version = "0.0.0-alpha.0" }
tempfile = "3"

[lints]
workspace = true
